### ISSUE TITLE
More Google accounts - Contacts (birth days) not shown

### ISSUE THREAD

**Issue by ivanslamek** [andstatus/todoagenda#68] opened 2021-03-26 09:16 UTC
Hi.

I am having more google accounts. In the "Calendars and Tasks" section I see Contacts only from one account - therefore the birthdays from other account (which is "primary") are not shown (I presume). 

Restart of the phone did not help.

My suggestion would be to build-in some "refresh" function, which would check all "calendars / birthdays" settings.

Regards
Ivan

![Screenshot_20210326-100318_Todo Agenda](https://user-images.githubusercontent.com/17784907/112609769-3c7d3880-8e1c-11eb-89af-6312bcfd4066.jpg)
![Screenshot_20210326-100357_Calendar](https://user-images.githubusercontent.com/17784907/112609771-3dae6580-8e1c-11eb-9c5e-757e21e4bcbf.jpg)

**Comment by yvolk** [comment] 2021-03-30 05:22
Hi @ivanslamek.
All changes in ToDo Agenda settings are applied by our app/widget immediately after closing the Settings screens. So your problem is not caused by some outdated settings.
Please try to follow these tips: https://github.com/andstatus/todoagenda/issues/37

**Closed** 2021-06-22 16:47 UTC
